
@startuml
skinparam defaultTextAlignment center
skinparam componentStyle uml2

skinparam activity {
    FontColor          white
    AttributeFontColor white
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #527BC6
    BorderColor        black
    ArrowColor         #222266
    ArrowFontSize      15
}

skinparam activityDiamond {
    FontColor          white
    AttributeFontColor white
    FontSize           17
    BackgroundColor    #527BC6
    BorderColor        black
}

:**Test Playbook**;
:check for samba version;

if (samba_version.stdout|version_compare(vulnerable_releases[ansible_distribution_major_version], '<=')) then (True)
    :check for vulnerable versions;
endif

if (not is_vuln|skipped) then (True)
    :update samba from yum if vulnerable;
endif

if (not is_vuln|skipped) then (True)
    :check for samba version;
endif

if (not is_vuln|skipped) then (True)
    :check that we are no longer vulnerable;
endif
:check for samba3x version;

if (samba3x_version.stdout|version_compare(vulnerable_3x[ansible_distribution_major_version], '<=')) then (True)
    :check for vulnerable versions;
endif

if (not is_vuln|skipped) then (True)
    :update samba3x from yum if vulnerable;
endif

if (not is_vuln|skipped) then (True)
    :check for samba3x version;
endif

if (not is_vuln|skipped) then (True)
    :check that we are no longer vulnerable;
endif
:check for samba4 version;

if (samba4_version.stdout|version_compare(vulnerable_4[ansible_distribution_major_version], '<=')) then (True)
    :check for vulnerable versions;
endif

if (not is_vuln|skipped) then (True)
    :update samba4 from yum if vulnerable;
endif

if (not is_vuln|skipped) then (True)
    :check for samba4 version;
endif

if (not is_vuln|skipped) then (True)
    :check that we are no longer vulnerable;
endif
@enduml